#! /bin/sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 6

bspc config focused_border_color "#$(getcolor.sh fg)"
bspc config normal_border_color "#$(getcolor.sh bg)"

# Make Zathura tiled. For some reason it starts up in floating mode otherwise
bspc rule -a Zathura state=tiled
bspc rule -a '*:soffice' state=tiled
