#! /bin/sh

# Start workspace notifications
[ -x "$HOME/bin/wm.sh" ] && $HOME/bin/wm.sh &


bspc monitor -d I II III IV V

bspc config borderless_monocle true

bspc config border_width 1
bspc config window_gap 6

bspc config focused_border_color "#$(getcolor.sh fg)"
bspc config normal_border_color "#$(getcolor.sh bg)"

# Make Zathura tiled. For some reason it starts up in floating mode otherwise
bspc rule -a Zathura state=tiled
bspc rule -a '*:soffice' state=tiled
